import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";


import { Suspense } from "react";
import { Analytics } from '@vercel/analytics/react';
import DefaultLayout from '@/components/templates/DefaultLayout';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Suspense>
          <meta  name="keywords" content=""/>
        </Suspense>
      </head>
      <DefaultLayout >
        {children}
        <Analytics/>
      </DefaultLayout>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
